function OUTPUT=PCESURROG(PCCOEFFS, MULTIIND, BASIS_SAMP_ALL)
%%% THIS FUNCTION FINDS THE RESPONSE OF THE PCE FROM THE MULTIINDICES AND BASIS_SAMP_ALLLES!!
%---------------------------------------------------------------------------------
RESPPCENEW=zeros(size(BASIS_SAMP_ALL,1),size(PCCOEFFS,2));
for SAMPITR = 1:size(BASIS_SAMP_ALL,1)
    MULTIIORTHOPOLY=multiorthopoly(MULTIIND,BASIS_SAMP_ALL(SAMPITR,:));
RESPPCENEW(SAMPITR,:) =sum(PCCOEFFS.*MULTIIORTHOPOLY);
end
OUTPUT=RESPPCENEW;
end
